config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  resources :events, except: [:destroy, :edit, :update]
  resources :game_types, only: [:create, :destroy]
  resources :users, only: [:create, :destroy]
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  date_time      :datetime         not null
#  minimum_number :integer          default(1), not null
#  location_id    :integer          not null
#  game_type_id   :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Event < ActiveRecord::Base
  validates_presence_of :name, :game_type_id, :location_id, :minimum_number

  belongs_to :location
  belongs_to :game_type
  has_and_belongs_to_many :users

  def pretty_date
    date_time.strftime('%b %e, %Y')
  end

  def pretty_time
    date_time.strftime('%l:%M %P %Z')
  end
end

app/models/game_type.rb
# == Schema Information
#
# Table name: game_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GameType < ActiveRecord::Base
  validates :name, presence: true, length: { in: 3..30 }

  has_many :events, dependent: :destroy
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :events
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  email      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  validates_presence_of :name, :email
  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy, :show]
  before_action :set_game_types, except: [:destroy]

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = ["Successsss!"]
      redirect_to action: :index
    else
      flash[:error] = @event.errors.full_messages
      render :new
    end
  end

  def destroy
    @event.destroy
  end

  def edit
  end

  def index
    @game_type_id = params[:game_type]
    now_ish = Time.now - 45.minutes
    @events = Event.where('date_time >= ?', now_ish).order(:date_time)
    @past_events = Event
      .where('date_time < ?', now_ish)
      .order(:date_time)
      .reverse_order
    if @game_type_id
      @events = @events.where(game_type_id: @game_type_id)
      @past_events = @past_events.where(game_type_id: @game_type_id)
    end
    @game_type_id = @game_type_id.to_i
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @new_user = User.new
  end

  def update
    if @event.update(event_params)
      redirect_to event_index_path(@event)
    else
      flash[:error] = @event.errors.full_messages
    end
  end

  private

  def event_params
    eps = params
      .require(:event)
      .permit(:name, :description, :game_type_id, :location_id, :minimum_number)

    if !params[:event][:location_text].empty?
      location = Location.create({ name: params[:event][:location_text] })
      eps[:location_id] = location.id
    end

    if !params[:event][:game_type_text].empty?
      game_type = GameType.create({ name: params[:event][:game_type_text] })
      eps[:game_type_id] = game_type.id
    end

    begin
      date_str = params[:event][:date] + params[:event][:time]
      # Add 2 hours due to dates constantly being 2 hours behind
      # may need to remove when DST is done in the fall (wtf right??)
      eps[:date_time] = Time.zone.parse(date_str) + 2.hours
    rescue
      puts 'Date Time invalid: ', params[:event][:date], params[:event][:time]
    end

    eps
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_game_types
    @game_types = GameType.all
    @new_game_type = GameType.new
  end
end

app/controllers/game_types_controller.rb
class GameTypesController < ApplicationController
  before_action :set_game_type, only: [:destroy, :show]

  def create
    @game_type = GameType.new(game_type_params)
    flash[:error] = @game_type.errors.full_messages unless @game_type.save
    redirect_to controller: :events, action: :index
  end

  def destroy
    @game_type.destroy
    redirect_to controller: :events, action: :index
  end

  def index
    @game_types = GameType.all
    @new_game_type = GameType.new
  end

  def new
    @game_type = GameType.new
  end

  def show
    @new_user = User.new
  end

  private

  def set_game_type
    @game_type = GameType.find(params[:id])
  end

  def game_type_params
    params.require(:game_type).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :set_event

  def create
    if @user.update(user_params)
      @user.events << @event unless @user.events.include?(@event)
      if @user.save
        flash[:notice] = ["Successsss!"]
      else
        flash[:error] = @user.errors.full_messages
      end
    else
      flash[:error] = @user.errors.full_messages
    end
    redirect_to action: :show, controller: :events, id: @event.id
  end

  def destroy
    redirect_to action: :show, controller: :events, id: @event.id
    @user.events.delete(@event)
  end

  private

  def set_event
    @event = Event.find(params[:user][:event_id])
  end

  def set_user
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = User.find_or_initialize_by(email: user_params[:email])
    end
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/game_types_helper.rb
module GameTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="events">
  <header class="clear-fix">
    <h1>Upcoming Events</h1>
  </header>
  <section class="clear-fix">
    <% if @events.length < 1 %>
      <p>No upcoming events :( </p>
      <p>You should create one!</p>
    <% end %>
      <div class="new-event">
        <%= button_to(
          'Add an event',
          new_event_path,
          form_class: "inline",
          method: :get
        )%>
      </div>
    <% @events.each do |event| %>
      <% game_on = event.minimum_number <= event.users.length %>
      <div class="event">
        <h2><%= link_to "#{event.name}", event_path(event) %>
          <% game_type = event.game_type.name %>
          <% unless event.name.downcase.include?(game_type.downcase) ||
            (defined?(@game_type_id) && @game_type_id > 0) %>
            <br>
            <span class="small"> (<%= game_type %>)</span>
          <% end %>
        </h2>

        <div class="game-on">
          <% if game_on %>
            <%= image_tag('game-on.png', size: '100x84') %>
          <% else %>
            <% number_needed = event.minimum_number - event.users.length %>
            <p><b><%= pluralize(number_needed, 'person') %></b> still needed!</p>
          <% end %>
        </div>

        <p>Where: <%= event.location.name %></p>
        <p>When: <%= event.pretty_date %> @ <%= event.pretty_time %></p>
        <%= button_to(
          "Join the fun!",
          event_path(event),
          method: :get,
          class: :join
        )%>
      </div>
    <% end %>
  </section>
  <header class="clear-fix">
    <h1>Past Events</h1>
  </header>
  <section class="clear-fix">
    <% if @past_events.length < 1 %>
      <p>No past events.</p>
    <% end %>
    <% @past_events.each do |event| %>
    <div class="event">
      <h2><%= link_to "#{event.name}", event_path(event) %>
        <% game_type = event.game_type.name %>
        <% unless event.name.downcase.include?(game_type.downcase) ||
          (defined?(@game_type_id) && @game_type_id > 0) %>
          <br>
          <span class="small"> (<%= game_type %>)</span>
        <% end %>
      </h2>
      <p>Where: <%= event.location.name %></p>
      <p>When: <%= event.pretty_date %> @ <%= event.pretty_time %></p>
    </div>
    <% end %>
  </section>
</div>

app/views/events/new.html.erb
<h1>Create a new event:</h1>
<%= button_to 'Cancel', events_path, method: :get, class: :cancel %>
<div class="new-event-form">
  <%= form_for(@event) do |f| %>
    <%= f.label 'Event name' %>
    <%= f.text_field :name, placeholder: 'Give the event a name' %>
    <%= f.label 'Event Details (optional)' %>
    <%= f.text_area :description, message: "A short description", size: "30x5" %>


    <%= f.label 'Event type' %>
    <div id="event-type-select">
      <%= f.collection_select(
        :game_type_id, GameType.all.order(:name), :id, :name,
        include_blank: 'Select an event type'
      ) %>
      <span>or </span><%= link_to 'create a new event type', '#' %>
    </div>
    <div id="event-type-text" class="hidden">
      <input name="event[game_type_text]" placeholder="Event type name">
      <span>bring back the</span> <%= link_to 'event type drop-down', '#' %>
    </div>
    <br>

    <%= f.label 'Location' %>
    <div id="location-select">
      <%= f.collection_select(
        :location_id, Location.all.order(:name), :id, :name,
        include_blank: 'Select a location'
      ) %>
      <span>or </span><%= link_to 'create a new location', '#' %>
    </div>
    <div id="location-text" class="hidden">
      <input name="event[location_text]" placeholder="Location name">
      <span>bring back the</span> <%= link_to 'location drop-down', '#' %>
    </div>
    <br>

    <%= f.label 'Date' %>
    <input name="event[date]" class="datepicker" placeholder="Pick a date">
    <%= f.label 'Time' %>
    <input name="event[time]" class="timepicker" placeholder="Pick a time">
    <%= f.label 'Minimum number of participants' %>
    <%= f.text_field :minimum_number %>
    <%= f.submit 'Enter', class: 'submit button' %>
  <% end %>
</div>

<script type="text/javascript">
  $('.datepicker').pickadate({
    min: true
  });
  $('.timepicker').pickatime({
    interval: 15,
    min: [6,0],
    max: [23,45]
  });

  $('#location-text a').click(function () {
    $('#location-text').addClass('hidden');
    $('#location-select').removeClass('hidden');
  });
  $('#location-select a').click(function () {
    $('#location-select').addClass('hidden');
    $('#location-text').removeClass('hidden');
  });

  $('#event-type-text a').click(function () {
    $('#event-type-text').addClass('hidden');
    $('#event-type-select').removeClass('hidden');
  });
  $('#event-type-select a').click(function () {
    $('#event-type-select').addClass('hidden');
    $('#event-type-text').removeClass('hidden');
  });
</script>

app/views/events/show.html.erb
<% game_on = @event.minimum_number <= @event.users.length %>
<div class="events">
  <div class="event">
    <h2><%= @event.name %>
      <% game_type = GameType.find(@event.game_type_id).name %>
      <% unless @event.name.downcase.include? game_type.downcase %>
        <br>
        <span class="small"> (<%= game_type %>)</span>
      <% end %>
    </h2>

    <div class="game-on">
      <% if game_on %>
      <%= image_tag('game-on.png', size: '100x84') %>
      <% else %>
      <% number_needed = @event.minimum_number - @event.users.length %>
      <p><b><%= pluralize(number_needed, 'person') %></b> still needed!</p>
      <% end %>
    </div>

    <% if !@event.description.nil? && @event.description.length > 0 %>
      <p><%= @event.description %></p>
    <% end %>
    <p>Where: <%= @event.location.name %></p>
    <p>When: <%= @event.pretty_date %> @ <%= @event.pretty_time %></p>
    <% if @event.users.count > 0 %>
    <p>Who: </p>
    <ol class='users'>
      <% @event.users.order(:name).each do |user| %>
      <li>
        <%= user.name %>
        <%= button_to(
          'X', user_path(user), method: :delete,
          form_class: 'inline', class: 'delete',
          params: { 'user[event_id]': @event.id }
        ) %>
      </li>
      <% end %>
    </ol>
    <% end %>
    <h3>Join the fun!</h3>
    <%= form_for(@new_user) do |f| %>
    <%= f.hidden_field :event_id, value: @event.id %>
    <%= f.label 'Your Name' %>
    <%= f.text_field :name %>
    <%= f.label 'Gmail handle' %>
    <%= f.text_field :email, class: 'email-input' %>
    <span>@asperasoft.com</span>
    <%= f.submit 'Sign Up!', class: 'submit' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unofficial Aspera Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/partials/header' %>
  <div class="nav-sidebar">
    <%= render 'layouts/partials/nav_sidebar' %>
  </div>
  <div class="main">
    <%= render 'layouts/partials/errors' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/partials/_errors.html.erb
<% errors = flash[:error] %>
<ul class='errors'>
  <% errors.each do |err| %>
    <li class=error><%= err %></li>
  <% end if errors %>
</ul>

app/views/layouts/partials/_header.html.erb
<div class="header">
  <a href='/'>
    <h1>(Unofficial) <%= image_tag('logo.png', size: '120x50') %> Events</h1>
  </a>
</div>

app/views/layouts/partials/_nav_sidebar.html.erb
<% @game_type_id = 0 unless defined?(@game_type_id) %>
<ul>
  <li class="game-type-link<%= @game_type_id == 0 ? ' selected' : '' %>">
    <%= link_to "All Events (#{Event.count})", events_path %>
  </li>
  <li class="new-event">
    <%= button_to(
      'Add an event',
      new_event_path,
      form_class: "inline",
      method: :get
    )%>
  </li>
</ul>
<hr>
<ul>
  <% @game_types.sort_by { |el| el.name }.each do |gt| %>
    <li class="game-type-link<%= @game_type_id == gt.id ? ' selected' : '' %>">
      <%= link_to(
        "#{gt.name} (#{gt.events.count})", events_path(game_type: gt.id)
      ) %>
    </li>
  <% end %>
</ul>
<div id="create-event-type">
  <input class="new-button button" type="button" value="Add New Event Type">
</div>
<%= form_for(@new_game_type, html: { id: 'new-event', class: 'hidden' }) do |f| %>
  <%= f.text_field :name, placeholder: 'Event type name' %>
  <%= f.submit 'New Event Type', class: 'button submit' %>
<% end %>

<script type="text/javascript">
  $('#create-event-type').click(function () {
    $('#new-event').removeClass('hidden');
    $('#create-event-type').addClass('hidden');
  })
</script>